index:
  path: /
  controller: App\Controller\HelloController::index

users:
  path: /users
  controller: App\Controller\HelloController::users

compute:
  path: /compute
  controller: App\Controller\HelloController::compute